### ISSUE TITLE
How to use this package

### ISSUE THREAD

**Issue by waitsfornone** [edx/snowflake_timetravel_table#11]
Hello. I would like to try out this materialization, but the package does not seem to be on the dbt package index at the time of this issue. Would someone possibly be able to tell me how I can install? Thank you.

**Comment by AbdouSeck** [comment]
Add the following in your `packages.yml` file
```yaml
packages:
  - git: "https://github.com/edx/snowflake_timetravel_table.git"
    revision: 0.0.4
```
The next time you run `dbt deps`, it should _theoretically_ work.
